//! The SOLBEAM parameter sheet, as Rust constants.
//!
//! @generated by `config/gen.py` from `config/params.json` -- do not
//! edit by hand.  `config/params.json` is the single source;
//! `docs/parameters.csv` is its human-readable projection and this file
//! is its Rust projection.  The generator refuses to run if the JSON and
//! the CSV disagree, so the document, the CSV and the code cannot drift.
//!
//! Regenerate with `python3 config/gen.py`.
//!
//! `difficulty.rs` includes this file by relative `#[path]` as well, so
//! the cw-144 rule's spacing, clamps and lookback come from the same
//! generated values without giving that module a Solana dependency (it
//! is `#[path]`-included by the plain `cargo test` vectors crate).
#![allow(dead_code)]

// -- lc --

/// `lc.window_hours` -- Window length (hours) -- `32 dec`.
///
/// How much BSV history the client keeps. Sets the deposit deadline
pub const WINDOW_HOURS: u64 = 32;

/// `lc.seconds_per_block` -- Target block spacing -- `600 mea`.
///
/// BSV's ten-minute target
pub const SECONDS_PER_BLOCK: u64 = 600;

/// `lc.window` -- Window length (records) -- `192 der`.
///
/// window_hours × 3600 / seconds_per_block. Bounded above by the account cap
pub const WINDOW: usize = (WINDOW_HOURS * 3600 / SECONDS_PER_BLOCK) as usize;

/// `lc.record_size` -- Bytes per header record -- `52 der`.
///
/// 32 hash + 16 chainwork + 4 time. Not configurable
pub const HEADER_RECORD_SIZE: usize = 52;

/// `lc.lookback` -- DAA lookback (records) -- `147 der`.
///
/// 144 + 3 for the median-of-three. Measured: 146 reproduces 0/324 headers, 147 reproduces 324/324
pub const LOOKBACK_RECORDS: u64 = 147;

/// `lc.lookback` -- DAA lookback (records) -- `147 der`.
///
/// 144 + 3 for the median-of-three. Measured: 146 reproduces 0/324 headers, 147 reproduces 324/324
pub const SEED_RECORDS: usize = 147;

/// `lc.floor` -- Confirmation depth -- `12 blocks built`.
///
/// MIN_CONFIRMATIONS, fixed in code, not a runtime parameter
pub const MIN_CONFIRMATIONS: u64 = 12;

/// `lc.max_staleness_slots` -- Freshness bound -- `54,000 slots (~6 h) built`.
///
/// How recent the last accepted header must be before release. A multiple of BSV block time — ~1,500 Solana slots per block. Implemented (StaleClient), untested on a local validator
pub const MAX_STALENESS_SLOTS: u64 = 54_000;

/// `lc.max_fork_batch` -- Headers per fork tx -- `12 mea`.
///
/// Set by the 1,232-byte transaction limit
pub const MAX_FORK_BATCH: usize = 12;

/// `lc.max_account_create` -- Solana account cap -- `10,240 bytes mea`.
///
/// A Solana limit, not a choice
pub const MAX_ACCOUNT_CREATE: usize = 10_240;

/// `lc.daa_clamp_low` -- Lower clamp -- `72 × 600 s mea`.
///
/// Multiplies seconds_per_block, not the averaging window
pub const DAA_CLAMP_LOW_MULTIPLIER: i64 = 72;

/// `lc.daa_clamp_high` -- Upper clamp -- `288 × 600 s mea`.
///
/// As above
pub const DAA_CLAMP_HIGH_MULTIPLIER: i64 = 288;

// -- v --

/// `v.maturity_blocks` -- Maturity -- `0 built`.
///
/// Staged mints wait this long before release. A stored parameter, not a constant, so governance can raise it without a redeploy. At 0 the vault is a pass-through and release/burn are a race. The designed value is 144 blocks
pub const DEFAULT_MATURITY_BLOCKS: u64 = 0;

// -- gov --

/// `gov.authority_timelock` -- Authority timelock -- `32 slots built`.
///
/// TIMELOCK_SLOTS, a PoC value. Applied to propose_authority_change / execute_authority_change / cancel_authority_change. Must be long enough to exit
pub const TIMELOCK_SLOTS: u64 = 32;

// -- m --

/// `m.token_decimals` -- solBSV decimals -- `8 mea`.
///
/// —
pub const TOKEN_DECIMALS: u8 = 8;

// -- fee --

/// `fee.redeem_bp` -- Peg-out fee (gross) -- `30 bp dec`.
///
/// As above
pub const REDEEM_FEE_BP: u64 = 30;

// -- po --

/// `po.payout_confirmations` -- Payout depth -- `6 BSV blocks built`.
///
/// BSV confirmations before a payout is provable. C_payout
pub const PAYOUT_CONFIRMATIONS: u64 = 6;

/// `po.challenge_window` -- Challenge window -- `144 BSV blocks built`.
///
/// W. Confirmations a payout needs before settling
pub const CHALLENGE_WINDOW: u64 = 144;

/// `po.deadline` -- Redemption deadline -- `216,000 slots built`.
///
/// How long a member has to pay before the holder may cancel. In Solana SLOTS, because a height deadline would never expire if the header feed stalled. NOTE: the earlier claim that this must exceed payout_confirmations + challenge_window does NOT hold at these values (216,000 slots against 150 BSV blocks). The pay-and-refund race is closed structurally instead -- cancel_redeem is refused while a claim is live.
pub const REDEEM_DEADLINE_SLOTS: u64 = 216_000;

/// `po.cancel_grace` -- Cancellation grace -- `0 built`.
///
/// Cancellation is immediate on expiry. A grace period would only delay the exit
pub const CANCEL_GRACE_SLOTS: u64 = 0;

/// `po.d_min` -- Minimum redemption -- `1,000,000 base units (0.01 BSV) built`.
///
/// Minimum redemption, so a claim's proof is worth the transaction fees to settle
pub const REDEEM_D_MIN: u64 = 1_000_000;

/// `po.max_pending` -- Concurrent redemption cap -- `64 built`.
///
/// Cap on concurrent pending redemptions, so the escrow cannot be used to make the program's per-instruction work unbounded
pub const MAX_PENDING_REDEMPTIONS: u64 = 64;

// -- fed --

/// `fed.script` -- Reserve deposit script -- `2-of-2 OP_CHECKMULTISIG dec, shape accepted in code built`.
///
/// OP_2 <gateway threshold key> <greycore key> OP_2 OP_CHECKMULTISIG. Both keys must sign; the Greycore polices every reserve spend. The committed code accepts this shape: is_reserve_multisig, MAX_SCRIPT_LEN = 71, DepositScript::SPACE = 84. The keys/quorum behind it are not built
pub const MAX_SCRIPT_LEN: usize = 71;
